spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: twitter-stream
                output:
                    destination: twitter-messages
            kafka:
                binder:
                    brokers: 192.168.99.100
                    zkNodes: 192.168.99.100